/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BurnTracker {
  export type UserStatsStruct = {
    totalGasUsed: BigNumberish;
    totalTransactions: BigNumberish;
    avaxBurned: BigNumberish;
  };

  export type UserStatsStructOutput = [
    totalGasUsed: bigint,
    totalTransactions: bigint,
    avaxBurned: bigint
  ] & { totalGasUsed: bigint; totalTransactions: bigint; avaxBurned: bigint };
}

export interface BurnTrackerInterface extends Interface {
  getFunction(
    nameOrSignature: "getMyStats" | "recordUsage" | "userStats"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GasTracked"): EventFragment;

  encodeFunctionData(
    functionFragment: "getMyStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordUsage",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userStats",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getMyStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userStats", data: BytesLike): Result;
}

export namespace GasTrackedEvent {
  export type InputTuple = [
    user: AddressLike,
    gasUsed: BigNumberish,
    txCount: BigNumberish
  ];
  export type OutputTuple = [user: string, gasUsed: bigint, txCount: bigint];
  export interface OutputObject {
    user: string;
    gasUsed: bigint;
    txCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BurnTracker extends BaseContract {
  connect(runner?: ContractRunner | null): BurnTracker;
  waitForDeployment(): Promise<this>;

  interface: BurnTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMyStats: TypedContractMethod<
    [],
    [BurnTracker.UserStatsStructOutput],
    "view"
  >;

  recordUsage: TypedContractMethod<
    [user: AddressLike, gasUsed: BigNumberish, txCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  userStats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalGasUsed: bigint;
        totalTransactions: bigint;
        avaxBurned: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMyStats"
  ): TypedContractMethod<[], [BurnTracker.UserStatsStructOutput], "view">;
  getFunction(
    nameOrSignature: "recordUsage"
  ): TypedContractMethod<
    [user: AddressLike, gasUsed: BigNumberish, txCount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalGasUsed: bigint;
        totalTransactions: bigint;
        avaxBurned: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "GasTracked"
  ): TypedContractEvent<
    GasTrackedEvent.InputTuple,
    GasTrackedEvent.OutputTuple,
    GasTrackedEvent.OutputObject
  >;

  filters: {
    "GasTracked(address,uint256,uint256)": TypedContractEvent<
      GasTrackedEvent.InputTuple,
      GasTrackedEvent.OutputTuple,
      GasTrackedEvent.OutputObject
    >;
    GasTracked: TypedContractEvent<
      GasTrackedEvent.InputTuple,
      GasTrackedEvent.OutputTuple,
      GasTrackedEvent.OutputObject
    >;
  };
}
