/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DCAFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allVaults"
      | "burnTracker"
      | "createVault"
      | "executionEngine"
      | "getAllVaults"
      | "getMyVault"
      | "owner"
      | "setBurnTracker"
      | "setExecutionEngine"
      | "triggerBatchDCA"
      | "triggerDCA"
      | "userVault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BurnTrackerSet"
      | "DCATriggered"
      | "ExecutionEngineSet"
      | "VaultCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allVaults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnTracker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executionEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setBurnTracker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutionEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerBatchDCA",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerDCA",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userVault",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "allVaults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executionEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMyVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBurnTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExecutionEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerBatchDCA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "triggerDCA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userVault", data: BytesLike): Result;
}

export namespace BurnTrackerSetEvent {
  export type InputTuple = [burnTracker: AddressLike];
  export type OutputTuple = [burnTracker: string];
  export interface OutputObject {
    burnTracker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DCATriggeredEvent {
  export type InputTuple = [vault: AddressLike, user: AddressLike];
  export type OutputTuple = [vault: string, user: string];
  export interface OutputObject {
    vault: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionEngineSetEvent {
  export type InputTuple = [executionEngine: AddressLike];
  export type OutputTuple = [executionEngine: string];
  export interface OutputObject {
    executionEngine: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [user: AddressLike, vault: AddressLike];
  export type OutputTuple = [user: string, vault: string];
  export interface OutputObject {
    user: string;
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DCAFactory extends BaseContract {
  connect(runner?: ContractRunner | null): DCAFactory;
  waitForDeployment(): Promise<this>;

  interface: DCAFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allVaults: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  burnTracker: TypedContractMethod<[], [string], "view">;

  createVault: TypedContractMethod<
    [_buyAmount: BigNumberish, _frequency: BigNumberish],
    [string],
    "nonpayable"
  >;

  executionEngine: TypedContractMethod<[], [string], "view">;

  getAllVaults: TypedContractMethod<[], [string[]], "view">;

  getMyVault: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setBurnTracker: TypedContractMethod<
    [_burnTracker: AddressLike],
    [void],
    "nonpayable"
  >;

  setExecutionEngine: TypedContractMethod<
    [_executionEngine: AddressLike],
    [void],
    "nonpayable"
  >;

  triggerBatchDCA: TypedContractMethod<
    [users: AddressLike[]],
    [void],
    "nonpayable"
  >;

  triggerDCA: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  userVault: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allVaults"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "burnTracker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<
    [_buyAmount: BigNumberish, _frequency: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executionEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllVaults"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMyVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBurnTracker"
  ): TypedContractMethod<[_burnTracker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExecutionEngine"
  ): TypedContractMethod<[_executionEngine: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerBatchDCA"
  ): TypedContractMethod<[users: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerDCA"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userVault"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "BurnTrackerSet"
  ): TypedContractEvent<
    BurnTrackerSetEvent.InputTuple,
    BurnTrackerSetEvent.OutputTuple,
    BurnTrackerSetEvent.OutputObject
  >;
  getEvent(
    key: "DCATriggered"
  ): TypedContractEvent<
    DCATriggeredEvent.InputTuple,
    DCATriggeredEvent.OutputTuple,
    DCATriggeredEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionEngineSet"
  ): TypedContractEvent<
    ExecutionEngineSetEvent.InputTuple,
    ExecutionEngineSetEvent.OutputTuple,
    ExecutionEngineSetEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;

  filters: {
    "BurnTrackerSet(address)": TypedContractEvent<
      BurnTrackerSetEvent.InputTuple,
      BurnTrackerSetEvent.OutputTuple,
      BurnTrackerSetEvent.OutputObject
    >;
    BurnTrackerSet: TypedContractEvent<
      BurnTrackerSetEvent.InputTuple,
      BurnTrackerSetEvent.OutputTuple,
      BurnTrackerSetEvent.OutputObject
    >;

    "DCATriggered(address,address)": TypedContractEvent<
      DCATriggeredEvent.InputTuple,
      DCATriggeredEvent.OutputTuple,
      DCATriggeredEvent.OutputObject
    >;
    DCATriggered: TypedContractEvent<
      DCATriggeredEvent.InputTuple,
      DCATriggeredEvent.OutputTuple,
      DCATriggeredEvent.OutputObject
    >;

    "ExecutionEngineSet(address)": TypedContractEvent<
      ExecutionEngineSetEvent.InputTuple,
      ExecutionEngineSetEvent.OutputTuple,
      ExecutionEngineSetEvent.OutputObject
    >;
    ExecutionEngineSet: TypedContractEvent<
      ExecutionEngineSetEvent.InputTuple,
      ExecutionEngineSetEvent.OutputTuple,
      ExecutionEngineSetEvent.OutputObject
    >;

    "VaultCreated(address,address)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
  };
}
