/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DCAVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "active"
      | "buyAmount"
      | "canExecute"
      | "executeDCA"
      | "executionCount"
      | "factory"
      | "frequency"
      | "getStatus"
      | "initialize"
      | "lastExecution"
      | "owner"
      | "pause"
      | "resume"
      | "totalInvested"
      | "updateSettings"
      | "withdraw"
      | "withdrawAVAX"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DCAExecuted"
      | "VaultPaused"
      | "VaultResumed"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "active", values?: undefined): string;
  encodeFunctionData(functionFragment: "buyAmount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "canExecute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeDCA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executionCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "frequency", values?: undefined): string;
  encodeFunctionData(functionFragment: "getStatus", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastExecution",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "resume", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalInvested",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateSettings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAVAX",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "active", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyAmount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "executeDCA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "frequency", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resume", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalInvested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAVAX",
    data: BytesLike
  ): Result;
}

export namespace DCAExecutedEvent {
  export type InputTuple = [amountSpent: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [amountSpent: bigint, timestamp: bigint];
  export interface OutputObject {
    amountSpent: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultPausedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultResumedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DCAVault extends BaseContract {
  connect(runner?: ContractRunner | null): DCAVault;
  waitForDeployment(): Promise<this>;

  interface: DCAVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  active: TypedContractMethod<[], [boolean], "view">;

  buyAmount: TypedContractMethod<[], [bigint], "view">;

  canExecute: TypedContractMethod<[], [boolean], "view">;

  executeDCA: TypedContractMethod<[], [boolean], "nonpayable">;

  executionCount: TypedContractMethod<[], [bigint], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  frequency: TypedContractMethod<[], [bigint], "view">;

  getStatus: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        _buyAmount: bigint;
        _frequency: bigint;
        _lastExecution: bigint;
        _nextExecution: bigint;
        _totalInvested: bigint;
        _executionCount: bigint;
        _active: boolean;
        _canExecute: boolean;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [_buyAmount: BigNumberish, _frequency: BigNumberish],
    [void],
    "nonpayable"
  >;

  lastExecution: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  resume: TypedContractMethod<[], [void], "nonpayable">;

  totalInvested: TypedContractMethod<[], [bigint], "view">;

  updateSettings: TypedContractMethod<
    [_buyAmount: BigNumberish, _frequency: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawAVAX: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "active"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "buyAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "canExecute"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "executeDCA"
  ): TypedContractMethod<[], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "executionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "frequency"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        _buyAmount: bigint;
        _frequency: bigint;
        _lastExecution: bigint;
        _nextExecution: bigint;
        _totalInvested: bigint;
        _executionCount: bigint;
        _active: boolean;
        _canExecute: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_buyAmount: BigNumberish, _frequency: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastExecution"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resume"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalInvested"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateSettings"
  ): TypedContractMethod<
    [_buyAmount: BigNumberish, _frequency: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawAVAX"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DCAExecuted"
  ): TypedContractEvent<
    DCAExecutedEvent.InputTuple,
    DCAExecutedEvent.OutputTuple,
    DCAExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VaultPaused"
  ): TypedContractEvent<
    VaultPausedEvent.InputTuple,
    VaultPausedEvent.OutputTuple,
    VaultPausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultResumed"
  ): TypedContractEvent<
    VaultResumedEvent.InputTuple,
    VaultResumedEvent.OutputTuple,
    VaultResumedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "DCAExecuted(uint256,uint256)": TypedContractEvent<
      DCAExecutedEvent.InputTuple,
      DCAExecutedEvent.OutputTuple,
      DCAExecutedEvent.OutputObject
    >;
    DCAExecuted: TypedContractEvent<
      DCAExecutedEvent.InputTuple,
      DCAExecutedEvent.OutputTuple,
      DCAExecutedEvent.OutputObject
    >;

    "VaultPaused()": TypedContractEvent<
      VaultPausedEvent.InputTuple,
      VaultPausedEvent.OutputTuple,
      VaultPausedEvent.OutputObject
    >;
    VaultPaused: TypedContractEvent<
      VaultPausedEvent.InputTuple,
      VaultPausedEvent.OutputTuple,
      VaultPausedEvent.OutputObject
    >;

    "VaultResumed()": TypedContractEvent<
      VaultResumedEvent.InputTuple,
      VaultResumedEvent.OutputTuple,
      VaultResumedEvent.OutputObject
    >;
    VaultResumed: TypedContractEvent<
      VaultResumedEvent.InputTuple,
      VaultResumedEvent.OutputTuple,
      VaultResumedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
