/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ExecutionEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BENQI_qiAVAX"
      | "LB_ROUTER"
      | "PRECISION"
      | "SLIPPAGE"
      | "USDC"
      | "WAVAX"
      | "_executeInternal"
      | "burnTracker"
      | "executeBatch"
      | "executeDCA"
      | "factory"
      | "factoryLocked"
      | "getConfig"
      | "isReady"
      | "setFactory"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DCAExecuted" | "DCAFailed" | "FactoryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BENQI_qiAVAX",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "LB_ROUTER", values?: undefined): string;
  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;
  encodeFunctionData(functionFragment: "SLIPPAGE", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "WAVAX", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_executeInternal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "burnTracker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executeDCA",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "factoryLocked",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getConfig", values?: undefined): string;
  encodeFunctionData(functionFragment: "isReady", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setFactory",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BENQI_qiAVAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "LB_ROUTER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SLIPPAGE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WAVAX", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_executeInternal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executeDCA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "factoryLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConfig", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isReady", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFactory", data: BytesLike): Result;
}

export namespace DCAExecutedEvent {
  export type InputTuple = [
    vault: AddressLike,
    user: AddressLike,
    usdcSpent: BigNumberish,
    avaxReceived: BigNumberish,
    qiTokens: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    user: string,
    usdcSpent: bigint,
    avaxReceived: bigint,
    qiTokens: bigint
  ];
  export interface OutputObject {
    vault: string;
    user: string;
    usdcSpent: bigint;
    avaxReceived: bigint;
    qiTokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DCAFailedEvent {
  export type InputTuple = [vault: AddressLike, reason: BytesLike];
  export type OutputTuple = [vault: string, reason: string];
  export interface OutputObject {
    vault: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FactoryUpdatedEvent {
  export type InputTuple = [oldFactory: AddressLike, newFactory: AddressLike];
  export type OutputTuple = [oldFactory: string, newFactory: string];
  export interface OutputObject {
    oldFactory: string;
    newFactory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExecutionEngine extends BaseContract {
  connect(runner?: ContractRunner | null): ExecutionEngine;
  waitForDeployment(): Promise<this>;

  interface: ExecutionEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BENQI_qiAVAX: TypedContractMethod<[], [string], "view">;

  LB_ROUTER: TypedContractMethod<[], [string], "view">;

  PRECISION: TypedContractMethod<[], [bigint], "view">;

  SLIPPAGE: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  WAVAX: TypedContractMethod<[], [string], "view">;

  _executeInternal: TypedContractMethod<
    [vault: AddressLike],
    [void],
    "nonpayable"
  >;

  burnTracker: TypedContractMethod<[], [string], "view">;

  executeBatch: TypedContractMethod<
    [vaults: AddressLike[]],
    [void],
    "nonpayable"
  >;

  executeDCA: TypedContractMethod<
    [vault: AddressLike],
    [boolean],
    "nonpayable"
  >;

  factory: TypedContractMethod<[], [string], "view">;

  factoryLocked: TypedContractMethod<[], [boolean], "view">;

  getConfig: TypedContractMethod<
    [],
    [
      [string, string, boolean] & {
        _factory: string;
        _burnTracker: string;
        _factoryLocked: boolean;
      }
    ],
    "view"
  >;

  isReady: TypedContractMethod<[], [boolean], "view">;

  setFactory: TypedContractMethod<
    [_factory: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BENQI_qiAVAX"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LB_ROUTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLIPPAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WAVAX"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "_executeInternal"
  ): TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "burnTracker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeBatch"
  ): TypedContractMethod<[vaults: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeDCA"
  ): TypedContractMethod<[vault: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "factoryLocked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getConfig"
  ): TypedContractMethod<
    [],
    [
      [string, string, boolean] & {
        _factory: string;
        _burnTracker: string;
        _factoryLocked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isReady"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setFactory"
  ): TypedContractMethod<[_factory: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DCAExecuted"
  ): TypedContractEvent<
    DCAExecutedEvent.InputTuple,
    DCAExecutedEvent.OutputTuple,
    DCAExecutedEvent.OutputObject
  >;
  getEvent(
    key: "DCAFailed"
  ): TypedContractEvent<
    DCAFailedEvent.InputTuple,
    DCAFailedEvent.OutputTuple,
    DCAFailedEvent.OutputObject
  >;
  getEvent(
    key: "FactoryUpdated"
  ): TypedContractEvent<
    FactoryUpdatedEvent.InputTuple,
    FactoryUpdatedEvent.OutputTuple,
    FactoryUpdatedEvent.OutputObject
  >;

  filters: {
    "DCAExecuted(address,address,uint256,uint256,uint256)": TypedContractEvent<
      DCAExecutedEvent.InputTuple,
      DCAExecutedEvent.OutputTuple,
      DCAExecutedEvent.OutputObject
    >;
    DCAExecuted: TypedContractEvent<
      DCAExecutedEvent.InputTuple,
      DCAExecutedEvent.OutputTuple,
      DCAExecutedEvent.OutputObject
    >;

    "DCAFailed(address,bytes)": TypedContractEvent<
      DCAFailedEvent.InputTuple,
      DCAFailedEvent.OutputTuple,
      DCAFailedEvent.OutputObject
    >;
    DCAFailed: TypedContractEvent<
      DCAFailedEvent.InputTuple,
      DCAFailedEvent.OutputTuple,
      DCAFailedEvent.OutputObject
    >;

    "FactoryUpdated(address,address)": TypedContractEvent<
      FactoryUpdatedEvent.InputTuple,
      FactoryUpdatedEvent.OutputTuple,
      FactoryUpdatedEvent.OutputObject
    >;
    FactoryUpdated: TypedContractEvent<
      FactoryUpdatedEvent.InputTuple,
      FactoryUpdatedEvent.OutputTuple,
      FactoryUpdatedEvent.OutputObject
    >;
  };
}
