/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iBenqiSol from "./IBenqi.sol";
export type { iBenqiSol };
import type * as iPythOracleSol from "./IPythOracle.sol";
export type { iPythOracleSol };
import type * as iTraderJoeSol from "./ITraderJoe.sol";
export type { iTraderJoeSol };
