/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iBenqiSol from "./IBenqi.sol";
export * as iPythOracleSol from "./IPythOracle.sol";
export * as iTraderJoeSol from "./ITraderJoe.sol";
