/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IPyth {
  export type PriceStruct = {
    price: BigNumberish;
    conf: BigNumberish;
    expo: BigNumberish;
    publishTime: BigNumberish;
  };

  export type PriceStructOutput = [
    price: bigint,
    conf: bigint,
    expo: bigint,
    publishTime: bigint
  ] & { price: bigint; conf: bigint; expo: bigint; publishTime: bigint };
}

export interface IPythInterface extends Interface {
  getFunction(
    nameOrSignature: "getPriceNoOlderThan" | "getUpdateFee" | "updatePriceFeeds"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPriceNoOlderThan",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUpdateFee",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePriceFeeds",
    values: [BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPriceNoOlderThan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUpdateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePriceFeeds",
    data: BytesLike
  ): Result;
}

export interface IPyth extends BaseContract {
  connect(runner?: ContractRunner | null): IPyth;
  waitForDeployment(): Promise<this>;

  interface: IPythInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPriceNoOlderThan: TypedContractMethod<
    [id: BytesLike, age: BigNumberish],
    [IPyth.PriceStructOutput],
    "view"
  >;

  getUpdateFee: TypedContractMethod<
    [updateData: BytesLike[]],
    [bigint],
    "view"
  >;

  updatePriceFeeds: TypedContractMethod<
    [updateData: BytesLike[]],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPriceNoOlderThan"
  ): TypedContractMethod<
    [id: BytesLike, age: BigNumberish],
    [IPyth.PriceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUpdateFee"
  ): TypedContractMethod<[updateData: BytesLike[]], [bigint], "view">;
  getFunction(
    nameOrSignature: "updatePriceFeeds"
  ): TypedContractMethod<[updateData: BytesLike[]], [void], "payable">;

  filters: {};
}
