/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILBRouter,
  ILBRouterInterface,
} from "../../../../contracts/interfaces/ITraderJoe.sol/ILBRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountOutMin",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256[]",
            name: "pairBinSteps",
            type: "uint256[]",
          },
          {
            internalType: "address[]",
            name: "tokenPath",
            type: "address[]",
          },
        ],
        internalType: "struct ILBRouter.Path",
        name: "path",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "swapExactTokensForTokens",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILBRouter__factory {
  static readonly abi = _abi;
  static createInterface(): ILBRouterInterface {
    return new Interface(_abi) as ILBRouterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ILBRouter {
    return new Contract(address, _abi, runner) as unknown as ILBRouter;
  }
}
